steps:
- name: gcr.io/moonrhythm-containers/golang:1.12.4-alpine3.9
  args: [go, build, -o, pikkanode, -ldflags, -w -s, main.go]
  env:
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=1
  - GOPROXY=https://gomodprox.com

- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/pikkanode:$COMMIT_SHA, '.']
- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/pikkanode:$COMMIT_SHA]

- name: gcr.io/cloud-builders/kubectl
  args: [set, image, -n, acoshift, deploy/pikkanode, pikkanode=gcr.io/$PROJECT_ID/pikkanode:$COMMIT_SHA]
  env:
  - CLOUDSDK_COMPUTE_ZONE=asia-southeast1
  - CLOUDSDK_CONTAINER_CLUSTER=cluster-0

images:
- gcr.io/$PROJECT_ID/pikkanode:$COMMIT_SHA
