# Sign Up

POST {{baseUrl}}/auth/signUp
Content-Type: application/json

{
    "username": "tester",
    "password": "123456"
}

###

# Sign In

POST {{baseUrl}}/auth/signIn
Content-Type: application/json

{
	"username": "tester",
	"password": "123456"
}

> {% client.global.set("auth_cookie", response.headers.valueOf('Set-Cookie').match(/(s=)([^;]*)/g)[0]) %}

###

# Sign Out

POST {{baseUrl}}/auth/signOut
Content-Type: application/json
Cookie: {{auth_cookie}}

{}

###

# Check

POST {{baseUrl}}/auth/check
Content-Type: application/json
Cookie: {{auth_cookie}}

{}

###
