# Profile

GET http://localhost:8080/me/profile
Cookie: {{auth_cookie}}

###

# Upload profile photo

POST http://localhost:8080/me/uploadProfilePhoto
Content-Type: multipart/form-data; boundary=----b
Cookie: {{auth_cookie}}

------b
Content-Disposition: form-data; name="photo"
Content-Type: image/jpg
Content-Length: 10

IMAGE_DATA
------b--

###

# Remove Work

POST http://localhost:8080/me/removeWork
Content-Type: application/json
Cookie: {{auth_cookie}}

{
  "id": "1"
}

###

# Get My Works

POST http://localhost:8080/me/getMyWorks
Content-Type: application/json
Cookie: {{auth_cookie}}

{
  "paginate": {
    "page": 1,
    "perPage": 20
  }
}

###

# Get My Favorite Works

POST http://localhost:8080/me/getMyFavoriteWorks
Content-Type: application/json
Cookie: {{auth_cookie}}

{
  "paginate": {
    "page": 1,
    "perPage": 20
  }
}

###

# Create Work

POST http://localhost:8080/me/createWork
Content-Type: multipart/form-data; boundary=----b
Cookie: {{auth_cookie}}

------b
Content-Disposition: form-data; name="photo"
Content-Type: image/jpg
Content-Length: 10

IMAGE_DATA
------b--

###

# Update Work

POST http://localhost:8080/me/updateWork
Content-Type: application/json
Cookie: {{auth_cookie}}

{
  "id": "1",
  "name": "test",
  "detail": "hello",
  "tags": ["a", "b"]
}

###