# Profile

GET http://localhost:8080/user/profile?username=tester2
Cookie: {{auth_cookie}}

###

# Follow

POST http://localhost:8080/user/follow
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "username": "tester2",
    "follow": true
}

###
