# Profile

GET {{baseUrl}}/user/profile?username=tester2
Cookie: {{auth_cookie}}

###

# Follow

POST {{baseUrl}}/user/follow
Content-Type: application/json
Cookie: {{auth_cookie}}

{
    "username": "tester2",
    "follow": true
}

###
