# Get Work

POST http://localhost:8080/work/get
Content-Type: application/json

{
    "id": "1"
}

###

# Favorite Work

POST http://localhost:8080/work/favorite
Content-Type: application/json

{
	"id": "1",
	"favorite": true
}

###

# Comment Work

POST http://localhost:8080/work/comment
Content-Type: application/json

{
  "id": "1",
  "content": "awesome!"
}

###