# Get Work

POST {{baseUrl}}/work/get
Content-Type: application/json

{
    "id": "1"
}

###

# Favorite Work

POST {{baseUrl}}/work/favorite
Content-Type: application/json

{
	"id": "1",
	"favorite": true
}

###

# Comment Work

POST {{baseUrl}}/work/comment
Content-Type: application/json

{
  "id": "1",
  "content": "awesome!"
}

###
